openapi: 3.0.0

info:
  title: Shinservice API
  description: Methods PI of Shinservice
  version: 1.0.0

servers:
  - url: http://shinapi.localhost
    description: Localhost develop server
tags:
  - name: Orders
    description: Данные по индивидуальным заказам
  - name: Sales
    description: Данные по индивидуальным продажам

paths:
  /order_for_delivery/{id}:
    get:
      tags:
        - "Orders"
      summary: "Загрузка заказа по ID"
      description: "Load order for delivery"
      operationId: "Load order"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        404:
          $ref: '#/components/schemas/404'

  /order_for_delivery/add:
    post:
      tags:
        - "Orders"
      summary: "Добавление заказа"
      description: "Add order for delivery"
      operationId: "Add order"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  description: данные
                  example: [ 1, 2 ]
              required:
                - residence
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  createdAt:
                    $ref: '#/components/schemas/DateTime'
        404:
          $ref: '#/components/schemas/404'

components:
  schemas:

    Order:
      description: Заказ
      type: object
      properties:
        mark:
          type: string
          description: Марка
          example: "010352870089138621kXREs"
        nomenclature:
          type: string
          description: Номенклатура
          example: "MICH 285/30 ZR19 Pilot Super Sport ZP (94Y)"

    400:
      description: Bad request
      type: string
      example: Invalid parameter
    401:
      description: Invalid credentials
      type: string
      example: Invalid credentials.
    404:
      description: Not found response
      type: string
      example: Not found