openapi: 3.0.0

info:
  title: Shinservice API
  description: Methods API of Shinservice
  version: 1.0.0

servers:
  - url: http://shinapi.localhost
    description: Localhost develop server
tags:
  - name: Proxy
    description: Прокси
  - name: Order Marks
    description: Данные по заказам
  - name: Sales Marks
    description: Данные по продажам

paths:
  /UploadOrderForDelivery:
    get:
      tags:
        - "Proxy"
      summary: "Загрузка заказа по ID"
      description: "Load order for delivery"
      operationId: "Load order"
      parameters:
        - in: query
          name: DocumentNumber
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mark'
        404:
          $ref: '#/components/schemas/404'

  /DownloadMarksToOrderForDelivery:
    post:
      tags:
        - "Proxy"
      summary: "Добавление заказа"
      description: "Add order for delivery"
      operationId: "Add order"
      parameters:
        - in: query
          name: DocumentNumber
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                 $ref: '#/components/schemas/Mark'
              required:
                - DocumentNumber
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mark'
        404:
          $ref: '#/components/schemas/404'

  /UploadSalesMark:
    get:
      tags:
        - "Proxy"
      summary: "Загрузка продажи по ID"
      description: "Load sales marks"
      operationId: "Load sales marks"
      parameters:
        - in: query
          name: DocumentNumber
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sales'
        404:
          $ref: '#/components/schemas/404'


  /DownloadSalesMark:
    post:
      tags:
        - "Proxy"
      summary: "Добавление продажи"
      description: "Add sale for delivery"
      operationId: "Add sale"
      parameters:
        - in: query
          name: DocumentNumber
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sales'
              required:
                - DocumentNumber
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mark'
        404:
          $ref: '#/components/schemas/404'


  /order_for_delivery/{id}:
    get:
      tags:
        - "Order Marks"
      summary: "Загрузка заказа по ID (custom)"
      description: "Load order for delivery"
      operationId: "Load order (custom)"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mark'
        404:
          $ref: '#/components/schemas/404'

#  /order_for_delivery/add:
#    post:
#      tags:
#        - "Order Marks"
#      summary: "Добавление заказа (custom)"
#      description: "Add order for delivery"
#      operationId: "Add order (custom)"
#      requestBody:
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                data:
#                  type: array
#                  description: данные
#                  example: [ 1, 2 ]
#              required:
#                - DocumentNumber
#      responses:
#        200:
#          description: OK
#          content:
#            application/json:
#              schema:
#                type: object
#                properties:
#                  id:
#                    type: string
#                  createdAt:
#                    $ref: '#/components/schemas/DateTime'
#        404:
#          $ref: '#/components/schemas/404'

  /sales_mark/{id}:
    get:
      tags:
        - "Sales Marks"
      summary: "Загрузка продажи по ID (custom)"
      description: "Load sales marks"
      operationId: "Load sales marks (custom)"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sales'
        404:
          $ref: '#/components/schemas/404'

#  /sales_mark/add:
#    post:
#      tags:
#        - "Sales Marks"
#      summary: "Добавление продажи"
#      description: "Add order for delivery"
#      operationId: "Add order (custom)"
#      requestBody:
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                data:
#                  type: array
#                  description: данные
#                  example: [ 1, 2 ]
#              required:
#                - DocumentNumber
#      responses:
#        200:
#          description: OK
#          content:
#            application/json:
#              schema:
#                type: object
#                properties:
#                  id:
#                    type: string
#                  createdAt:
#                    $ref: '#/components/schemas/DateTime'
#        404:
#          $ref: '#/components/schemas/404'

components:
  schemas:

    Mark:
      description: Заказ
      type: object
      properties:
        Марка:
          type: string
          description: Марка
          example: "010352870089138621kXREs"
        Номенклатура:
          type: string
          description: Номенклатура
          example: "MICH 285/30 ZR19 Pilot Super Sport ZP (94Y)"

    Goods:
      description: Товар
      type: object
      properties:
        Номенклатура:
          type: string
          description: Номенклатура
          example: "MICH 285/30 ZR19 Pilot Super Sport ZP (94Y)"
        Количество:
          type: integer
          description: Количество
          example: 2

    Sales:
      description: Продажа
      type: object
      properties:
        НомерДокументаРасхода:
          type: string
          description: Номер Документа Расхода
          example: "010352870089138621kXREs"
        Товары:
          type: array
          items:
            $ref: '#/components/schemas/Goods'
        Марки:
          type: array
          items:
            $ref: '#/components/schemas/Mark'
        ТолькоПоПереченюМарок:
          type: boolean
          description: Только По Переченю Марок
          example: false

    SalesMark:
      description: Продажа
      properties:
        Status:
          type: boolean
          description: Статус
          example: false
        Result:
          type: array
          items:
            $ref: '#/components/schemas/Sales'

    400:
      description: Bad request
      type: string
      example: Invalid parameter
    401:
      description: Invalid credentials
      type: string
      example: Invalid credentials.
    404:
      description: Not found response
      type: string
      example: Not found